// PaperSection.tsx
// Textured paper section with embossed / letterpress text. React + Tailwind (v3.3+ or v4) + TypeScript.
//
// USAGE
//   <PaperSection
//     headingFont="'Playfair Display', serif"
//     bodyFont="'Inter', sans-serif"
//   >
//     <Emboss as="h1">Field Notes</Emboss>
//     <Letterpress as="h2">Spring collection</Letterpress>
//     <p>Regular high-contrast body copy goes here.</p>
//   </PaperSection>
//
// FONTS
//   Load your fonts however you normally do (Google Fonts <link>, @fontsource,
//   next/font...) and pass the family strings as props. Heavy weights work
//   best for embossed headings; thin weights turn to mush.

import React from "react";

// Grain generated by the browser: no image files needed.
function hexToRgb01(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  const full = h.length === 3 ? h.split("").map((c) => c + c).join("") : h;
  const n = parseInt(full, 16);
  return [((n >> 16) & 255) / 255, ((n >> 8) & 255) / 255, (n & 255) / 255];
}

function makeNoise(color: string, strength: number, frequency: number) {
  const [r, g, b] = hexToRgb01(color).map((v) => v.toFixed(3));
  // Alpha row = contrast boost (k * noise + offset), so the grain reads as
  // speckle rather than a uniform haze.
  const k = (strength * 3).toFixed(2);
  const o = (-strength).toFixed(2);
  const matrix = `0 0 0 0 ${r} 0 0 0 0 ${g} 0 0 0 0 ${b} 0 0 0 ${k} ${o}`;
  return `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='300' height='300'%3E%3Cfilter id='n' color-interpolation-filters='sRGB'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='${frequency}' numOctaves='4' stitchTiles='stitch'/%3E%3CfeColorMatrix values='${matrix}'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")`;
}

const LIGHT =
  "radial-gradient(ellipse at 50% 0%, rgba(255,255,255,.55), transparent 70%)";

type PaperSectionProps = {
  children: React.ReactNode;
  /** Base paper color. Change for white, kraft, grey... */
  paper?: string;
  /** Grain color (hex). Darker than the paper = visible speckle. */
  grainColor?: string;
  /** Grain strength, 0 to 1. Try 0.3 subtle, 0.6 obvious. */
  grainStrength?: number;
  /** Grain fineness: ~0.4 rough and blotchy, ~1.0 fine and dusty. */
  grainFrequency?: number;
  /** CSS font-family string used by Emboss / Letterpress */
  headingFont?: string;
  /** CSS font-family string for everything else in the section */
  bodyFont?: string;
  /** Classes for the outer <section> (vertical padding lives here) */
  className?: string;
  /** Classes for the inner wrapper. Empty by default (children keep their own width). Pass e.g. "mx-auto max-w-3xl px-6" for a narrow text column */
  innerClassName?: string;
};

// Custom properties aren't part of React.CSSProperties, so extend it.
type PaperStyle = React.CSSProperties & {
  "--paper": string;
  "--heading-font": string;
};

export function PaperSection({
  children,
  paper = "#ece4d3",
  grainColor = "#5a4a30",
  grainStrength = 0.6,
  grainFrequency = 0.8,
  headingFont = "Georgia, serif",
  bodyFont = "system-ui, sans-serif",
  className = "",
  innerClassName = "",
}: PaperSectionProps) {
  const style: PaperStyle = {
    "--paper": paper,
    "--heading-font": headingFont,
    backgroundColor: paper,
    backgroundImage: `${makeNoise(grainColor, grainStrength, grainFrequency)}, ${LIGHT}`,
    fontFamily: bodyFont,
  };

  return (
    <section
      className={`relative shadow-[inset_0_0_80px_rgba(120,90,40,0.18)] ${className}`}
      style={style}
    >
      <div className={innerClassName}>{children}</div>
    </section>
  );
}

type HeadingProps = {
  as?: React.ElementType;
  className?: string;
  style?: React.CSSProperties;
  children: React.ReactNode;
};

// Raised text: same colour as the paper, highlight top-left, shadow bottom-right.
export function Emboss({
  as: Tag = "h1",
  className = "",
  style,
  children,
}: HeadingProps) {
  return (
    <Tag
      className={
        `text-6xl font-extrabold leading-tight tracking-tight text-[#e4dccb] ` +
        `[text-shadow:-1px_-1px_1px_rgba(255,255,255,.9),1px_1px_2px_rgba(0,0,0,.28)] ` +
        className
      }
      style={{ fontFamily: "var(--heading-font)", ...style }}
    >
      {children}
    </Tag>
  );
}

// Pressed-in text: slightly darker than the paper, light catching the lower edge.
export function Letterpress({
  as: Tag = "h2",
  className = "",
  style,
  children,
}: HeadingProps) {
  return (
    <Tag
      className={
        `text-4xl font-bold leading-snug text-[#b5a888] ` +
        `[text-shadow:0_1px_0_rgba(255,255,255,.75),0_-1px_0_rgba(0,0,0,.15)] ` +
        className
      }
      style={{ fontFamily: "var(--heading-font)", ...style }}
    >
      {children}
    </Tag>
  );
}

// Demo, delete once you've wired it into your page.
export default function Demo() {
  return (
    <PaperSection
      headingFont="'Playfair Display', Georgia, serif"
      bodyFont="'Inter', system-ui, sans-serif"
      className="py-24"
      innerClassName="mx-auto max-w-3xl px-6"
    >
      <Emboss>Field Notes</Emboss>
      <Letterpress className="mt-4">Spring collection</Letterpress>
      <p className="mt-8 max-w-prose text-lg leading-relaxed text-stone-800">
        Body copy stays dark and high contrast. Only the headings get the
        pressed-paper treatment.
      </p>
    </PaperSection>
  );
}