export const publicRoutes = [
  { path: "/", layout: "main", page: "home" },
  { path: "/about-us", layout: "main", page: "aboutUs" },
  { path: "/team", layout: "main", page: "team" },
  { path: "/case-studies", layout: "main", page: "caseStudies" },
  { path: "/services", layout: "main", page: "services" },
  { path: "/services/service", layout: "main", page: "service" },
  { path: "/services/customs", layout: "main", page: "customs" },
  { path: "/services/distribution", layout: "main", page: "distribution" },
  { path: "/services/fmcg", layout: "main", page: "fmcg" },
  { path: "/services/freight", layout: "main", page: "freight" },
  { path: "/services/import-export", layout: "main", page: "importExport" },
  { path: "/services/supply-chain", layout: "main", page: "supplyChain" },
  { path: "/services/warehousing", layout: "main", page: "warehousing" },
  { path: "/industries", layout: "main", page: "industries" },
  { path: "/industries/agriculture", layout: "main", page: "agriculture" },
  { path: "/industries/cold-chain", layout: "main", page: "coldChain" },
  { path: "/industries/e-commerce", layout: "main", page: "eCommerce" },
  { path: "/industries/fmcg-industry", layout: "main", page: "fmcgIndustry" },
  { path: "/industries/food-beverages", layout: "main", page: "foodBeverages" },
  { path: "/industries/horeca", layout: "main", page: "horeca" },
  { path: "/industries/retail", layout: "main", page: "retail" },
  { path: "/contact", layout: "simple", page: "contact" },
  { path: "/get-a-quote", layout: "simple", page: "contact" },
  { path: "/partner-contact", layout: "simple", page: "partnerContact" },
  { path: "/be-our-partner", layout: "simple", page: "beOurPartner" },
  { path: "/careers", layout: "main", page: "careers" },
  { path: "/privacy-policy", layout: "simple", page: "privacyPolicy" },
  { path: "/terms-of-service", layout: "simple", page: "termsOfService" },
  { path: "/nfc-card", layout: "bare", page: "nfcCard" },
] as const;

export type PublicRoute = (typeof publicRoutes)[number];
export type PublicPage = PublicRoute["page"];
export type RouteLayout = PublicRoute["layout"];

export const legacyRedirects = [
  { path: "/aboutUs", to: "/about-us" },
  { path: "/AboutUs", to: "/about-us" },
  { path: "/Home", to: "/" },
  { path: "/CTA", to: "/get-a-quote" },
  { path: "/cta", to: "/get-a-quote" },
  { path: "/Contact", to: "/contact" },
  { path: "/Services", to: "/services" },
  { path: "/Industries", to: "/industries" },
  { path: "/Stats", to: "/#stats" },
  { path: "/How_it_works", to: "/#how-it-works" },
  { path: "/how-we-work", to: "/#how-it-works" },
  { path: "/stats", to: "/#stats" },
  { path: "/BeOurPartner", to: "/be-our-partner" },
  { path: "/partner", to: "/be-our-partner" },
  { path: "/partner_contact", to: "/partner-contact" },
  { path: "/privacy_policy", to: "/privacy-policy" },
  { path: "/terms_of_service", to: "/terms-of-service" },
  { path: "/services/impo-expo", to: "/services/import-export" },
  { path: "/services/import_export", to: "/services/import-export" },
  { path: "/services/supply_chain", to: "/services/supply-chain" },
  { path: "/services/Supply_chain", to: "/services/supply-chain" },
  { path: "/services/TCL", to: "/industries/cold-chain" },
  { path: "/industries/cold_chain", to: "/industries/cold-chain" },
  { path: "/industries/e_commerce", to: "/industries/e-commerce" },
  { path: "/industries/fmcg_industry", to: "/industries/fmcg-industry" },
  { path: "/industries/food_beverages", to: "/industries/food-beverages" },
  { path: "/nfcCard", to: "/nfc-card" },
] as const;
